### ISSUE TITLE
Remove `pooch` dependancy?

### ISSUE THREAD

**Issue by benoistlaurent** [MDverse/mdws#24]
# Problem

`scripts/download_files.py` requires `pooch` to download files, which requires `lzma`.

This is problematic for users who have a fully working Python, without the lzma library.

As `mdws` does not require to compress/uncompress lzma files, it's quite a shame that a user still needs Python's lzma library.

# Suggested solution

Use `urllib` and/or `request` and/or `md5` to remove `pooch` dependency.

**Comment by pierrepo** [comment]
Since the [`lzma`](https://docs.python.org/3/library/lzma.html) module is in the standard library. `pooch` looks still a valid option.

Maybe we could close this issue.
