### ISSUE TITLE
Query Zenodo with filetypes

### ISSUE THREAD

**Issue by pierrepo** [MDverse/mdws#3]
We could find datasets in Zenodo from the following keywords:
- tpr
- gro
- mdp
- ndx
- xtc
- trr
- crd
- xsc
- prmtop

**Comment by pierrepo** [comment]
@lisabdj could you please have a look ?

**Comment by j0kaso** [comment]
I suppose we can close this @pierrepo as mentioned above (from the merge)

**Comment by pierrepo** [comment]
Oops. Yes...
